"""Build the replay firmware's data header from a recorded rig log.

``nano_lsi_replay`` (``firmware/nano_lsi_replay/``) has no GPS or IMU of its
own: it plays a recorded drive's new fixes back through two on-chip
``LsiFilter`` instances the way ``nano_lsi_log`` feeds them, without the
zero-velocity update, so the two-axis hot path can be timed and its float32
output checked against a float64 replay of the same algebra. This module
reduces a rig CSV to that replay vector and renders it as the header the
sketch ``#include``s.

Run: ``python -m dtfit_hardware.tools.make_replay [log.csv]``. The recorded
drive is private and not part of the repository; ``$DTFIT_RIG_DATA`` or
``dtfit_hardware/data/`` are where a checkout keeps it (see
``compare_real.rig_log``).
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

from dtfit_hardware import compare_real as C

HERE = Path(__file__).resolve().parent
FIRMWARE = HERE.parent / "firmware"
REPLAY_HEADER = FIRMWARE / "nano_lsi_replay" / "replay_vec.h"


def from_log(path: str) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Reduce a rig CSV to the replay vector the firmware needs.

    Args:
        path: rig log CSV, the format :func:`compare_real.load_log` reads.

    Returns:
        ``(t, e, n)``, each ``float32`` of shape ``(n_fixes,)``: seconds since
        the first fix, and the local east / north metres of every new GPS fix
        (:func:`compare_real.to_enu` about the first fix).
    """
    d = C.load_log(path)
    enu, _ = C.to_enu(d["lat"], d["lon"], d["alt_m"])
    t = d["t"].astype(np.float32)
    e = enu[:, 0].astype(np.float32)
    n = enu[:, 1].astype(np.float32)
    return t, e, n


def _lit(v: float) -> str:
    """One value as a valid C float literal, decimal or exponent, ``f``-suffixed."""
    s = f"{float(v):.9g}"
    return (s if ("." in s or "e" in s) else s + ".0") + "f"


def _carr(name: str, a: np.ndarray) -> str:
    body = ", ".join(_lit(v) for v in a)
    return f"static const float {name}[RP_N] = {{{body}}};"


def render(t: np.ndarray, e: np.ndarray, n: np.ndarray, source: str) -> str:
    """Render ``replay_vec.h`` text from a replay vector.

    ``.9g`` keeps every ``float32`` value's decimal round trip exact (see
    :func:`read`), at the shortest literal that does so.

    Args:
        t: seconds since the first fix, shape ``(n_fixes,)``.
        e: local east metres, shape ``(n_fixes,)``.
        n: local north metres, shape ``(n_fixes,)``.
        source: name of the log the vector came from, recorded in a comment.
    """
    return "\n".join([
        f"// Generated by make_replay.py from {source}.",
        "#pragma once", f"#define RP_N {t.size}",
        _carr("RP_T", t), _carr("RP_E", e), _carr("RP_NN", n), ""])


def write(path: str, out: Path = REPLAY_HEADER) -> Path:
    """Write the replay header from a rig log.

    Args:
        path: rig log CSV to reduce, via :func:`from_log`.
        out: header to write; defaults to the replay sketch's own
            ``replay_vec.h``, which is generated, private and gitignored.

    Returns:
        The path written.
    """
    t, e, n = from_log(path)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(t, e, n, Path(path).name), encoding="utf-8")
    return out


def read(path: Path = REPLAY_HEADER) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Parse a generated ``replay_vec.h`` back into ``(t, e, n)``.

    Args:
        path: header to parse; defaults to the replay sketch's own.

    Returns:
        ``(t, e, n)``, each ``float32``, the same vector :func:`from_log`
        produced.

    Raises:
        FileNotFoundError: the header is missing (private, not committed).
    """
    text = path.read_text(encoding="utf-8")

    def _row(name: str) -> np.ndarray:
        body = text.split(f"{name}[RP_N] = {{", 1)[1].split("}", 1)[0]
        return np.array([float(v.rstrip("f")) for v in body.split(",")],
                         dtype=np.float32)

    return _row("RP_T"), _row("RP_E"), _row("RP_NN")


if __name__ == "__main__":
    import sys

    import dtfit_hardware

    log = sys.argv[1] if len(sys.argv) > 1 else str(
        Path(dtfit_hardware.__file__).parent / "data" /
        "drive_5hz_20260702_182933.csv")
    t, e, n = from_log(log)
    write(log)
    print(f"{t.size} fixes, {t[-1]:.1f} s, extent E {e.min():.0f}..{e.max():.0f} m, "
          f"N {n.min():.0f}..{n.max():.0f} m")
